# deploy-preview.yaml

# Workflow to build and deploy site to Vercel using Hugo
# Name of Workflow
name: deploy-preview

# Controls when the action will run. Triggers the workflow on push
# events but only for the develop branch
on:
  push:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-preview"
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:

    # Initiate deployment status
    - name: Start Deployment
      uses: bobheadxi/deployments@v0.4.3
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: Preview

    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'

    - name: Update Service Worker
      run: |
        npm install replace-in-files
        replace-in-files --regex=\"CACHE_VERSION = \\d+\" --replacement=\"CACHE_VERSION = ${GITHUB_RUN_NUMBER}\" ./static/sw.js

    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.79.1'

    - name: Build
      run: hugo -v

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      id: vercel-action
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required
        github-comment: false
        #vercel-args: '--prod' #Optional
        working-directory: public

    # Update deployment status
    - name: Update Deployment Status
      uses: bobheadxi/deployments@v0.4.3
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        env_url: ${{ steps.vercel-action.outputs.preview-url }}
